#
# ONCRPC Api Enable Section
#

CM_ENABLE := 1
GSDI_EXP_ENABLE := 1
GSTK_EXP_ENABLE := 1
#MVS_ENABLE := 1
MMGSDILIB_ENABLE := 1
NV_ENABLE := 1
OEM_RAPI_ENABLE := 1
PDAPI_ENABLE := 1
PDSM_ATL_ENABLE := 1
PING_MDM_ENABLE := 1
#SND_ENABLE := 1
UIM_ENABLE := 1
WMS_ENABLE := 1

#
# RPCGEN Api Enable Section
#

#PING_MDM_RPCGEN_ENABLE := 1
#OEM_RAPI_RPCGEN_ENABLE := 1

